//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneProje.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_KutuphaneEntities : DbContext
    {
        public DB_KutuphaneEntities()
            : base("name=DB_KutuphaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_CEZALAR> TBL_CEZALAR { get; set; }
        public virtual DbSet<TBL_HAREKETLER> TBL_HAREKETLER { get; set; }
        public virtual DbSet<TBL_KASA> TBL_KASA { get; set; }
        public virtual DbSet<TBL_KATEGORILER> TBL_KATEGORILER { get; set; }
        public virtual DbSet<TBL_KITAPLAR> TBL_KITAPLAR { get; set; }
        public virtual DbSet<TBL_PERSONELLER> TBL_PERSONELLER { get; set; }
        public virtual DbSet<TBL_UYELER> TBL_UYELER { get; set; }
        public virtual DbSet<TBL_YAZARLAR> TBL_YAZARLAR { get; set; }
        public virtual DbSet<TBL_HAKKIMIZDA> TBL_HAKKIMIZDA { get; set; }
        public virtual DbSet<TBL_ILETISIM> TBL_ILETISIM { get; set; }
        public virtual DbSet<TBL_MESAJLAR> TBL_MESAJLAR { get; set; }
        public virtual DbSet<TBL_DUYURULAR> TBL_DUYURULAR { get; set; }
    
        public virtual ObjectResult<string> Eniyipersonel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Eniyipersonel");
        }
    
        public virtual ObjectResult<string> Enaktifuye()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Enaktifuye");
        }
    
        public virtual ObjectResult<string> Eniyikitap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Eniyikitap");
        }
    
        public virtual ObjectResult<string> Yazar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Yazar");
        }
    
        public virtual ObjectResult<string> YAYINEVI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("YAYINEVI");
        }
    
        public virtual ObjectResult<string> KATEGORI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("KATEGORI");
        }
    }
}
